-- Creates a table and database
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS 
hbtn_0d_usa.states (
PRIMARY KEY(id), id INT AUTO_INCREMENT UNIQUE NOT NULL, name VARCHAR(256) NOT NULL);
