-- Creates a database and table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (id INT UNIQUE AUTO_GENERATED NOT NULL PRIMARY KEY, name VARCHAR(256) NOT NULL);
